# Generated by Django 6.0.2 on 2026-05-24 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系统名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='系统编码')),
                ('description', models.TextField(blank=True, verbose_name='系统描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统',
                'verbose_name_plural': '系统管理',
            },
        ),
        migrations.CreateModel(
            name='RequirementDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('content', models.TextField(verbose_name='文档内容')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_requirements', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.system', verbose_name='所属系统')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.system', verbose_name='所属系统'),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='测试计划标题')),
                ('description', models.TextField(blank=True, verbose_name='测试计划描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testplans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='core.system', verbose_name='所属系统')),
                ('test_cases', models.ManyToManyField(blank=True, related_name='test_plans', to='core.testcase', verbose_name='关联测试用例')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
            },
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['name'], name='core_system_name_e85edb_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['code'], name='core_system_code_8eaf27_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['status'], name='core_system_status_d3e6da_idx'),
        ),
    ]
