# Generated by Django 6.0.2 on 2026-06-05 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_system_requirementdoc_testcase_system_testplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='current_version',
            field=models.IntegerField(default=1, verbose_name='当前版本号'),
        ),
        migrations.CreateModel(
            name='TestExecutionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='批次状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_batches', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_cases', models.ManyToManyField(blank=True, related_name='execution_batches', to='core.testcase', verbose_name='关联测试用例')),
            ],
            options={
                'verbose_name': '测试执行批次',
                'verbose_name_plural': '测试执行批次',
            },
        ),
        migrations.CreateModel(
            name='TestExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('error', '异常')], default='running', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('log', models.TextField(blank=True, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tests', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='core.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(verbose_name='版本快照')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例版本',
                'verbose_name_plural': '用例版本',
                'ordering': ['-version_number'],
                'unique_together': {('test_case', 'version_number')},
            },
        ),
    ]
