# Generated by Django 6.0.2 on 2026-06-05 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testcase_current_version_testexecutionbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_data', models.JSONField(verbose_name='报告数据')),
                ('summary', models.TextField(blank=True, verbose_name='报告摘要')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/', verbose_name='PDF 文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.testexecutionbatch', verbose_name='关联执行批次')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system', verbose_name='所属系统')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
