# Generated by Django 5.0.14 on 2026-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_hash', models.CharField(db_index=True, max_length=64, verbose_name='文档内容Hash')),
                ('content_preview', models.TextField(blank=True, verbose_name='内容预览')),
                ('quality_score', models.JSONField(default=dict, verbose_name='质量评分')),
                ('completeness', models.JSONField(default=dict, verbose_name='完整度检查')),
                ('consistency', models.JSONField(default=dict, verbose_name='一致性/冲突检测')),
                ('risk_identification', models.JSONField(default=dict, verbose_name='风险识别')),
                ('category_stats', models.JSONField(default=dict, verbose_name='需求分类统计')),
                ('testability', models.JSONField(default=dict, verbose_name='可测试性评级')),
                ('generation_strategy', models.JSONField(blank=True, default=dict, verbose_name='生成策略')),
                ('total_sections', models.IntegerField(default=0, verbose_name='总章节数')),
                ('word_count', models.IntegerField(default=0, verbose_name='总字数')),
                ('analysis_version', models.CharField(default='1.0', max_length=20, verbose_name='分析版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '需求分析记录',
                'verbose_name_plural': '需求分析记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
