# Generated by Django 5.0.14 on 2026-06-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requirementanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='adopted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='采纳/拒绝时间'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='adoption_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='adoption_status',
            field=models.CharField(choices=[('pending', '待审核'), ('adopted', '已采纳'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='采纳状态'),
        ),
    ]
