# Generated by Django 5.0.14 on 2026-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requirementanalysis_adopted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='content',
            field=models.TextField(blank=True, verbose_name='完整文档内容'),
        ),
    ]
