# Generated by Django 5.0.14 on 2026-06-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requirementanalysis_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_analyses', to='core.system', verbose_name='所属系统'),
        ),
    ]
