# Generated by Django 6.0.2 on 2026-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_requirementanalysis_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='brd_type',
            field=models.CharField(default='business_requirement', max_length=50, verbose_name='文档类型'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='srs_content',
            field=models.JSONField(blank=True, default=dict, verbose_name='SRS内容'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='srs_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SRS生成时间'),
        ),
    ]
