# Generated by Django 6.0.2 on 2026-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_srs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='srs_adopted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SRS采纳/拒绝时间'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='srs_adoption_status',
            field=models.CharField(choices=[('pending', '待审核'), ('adopted', '已采纳'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='SRS采纳状态'),
        ),
    ]
